TASK_PICK = 0
START_IRREGULAR_VERBS = 1
IRREGULAR_VERBS = 11

START_TRANSLATE_UA_EN = 2
TRANSLATE_UA_EN = 21

START_IRREGULAR_VERBS_PRACTICE = 3
IRREGULAR_VERBS_PRACTICE = 31

START_PHRASAL_VERBS = 4
PHRASAL_VERBS_CATEGORY = 41
PHRASAL_VERBS = 42

START_STATIVE_DYNAMIC_VERBS = 5
STATIVE_DYNAMIC_VERBS = 52